en.wikipedia:
    # The name of the database (without the trailing _p).
    database: enwiki

    # The 'index' page, which lists all the configured WikiProjects in a formatted table.
    index: 'User:Community Tech bot/Popular pages'

    # The configuration page, where you add configuration for individual WikiProjects.
    config: 'User:Community Tech bot/Popular pages config.json'

    # The category that the individual reports should be placed in.
    category: 'Category:Lists of popular pages by WikiProject'

ar.wikipedia:
    database: arwiki
    index: 'ويكيبيديا:قائمة الصفحات الأكثر مشاهدة حسب مشروع الويكي'
    config: 'ويكيبيديا:قائمة الصفحات الأكثر مشاهدة حسب مشروع الويكي/الإعدادات.json'
    category: 'تصنيف:قائمة الصفحات الأكثر مشاهدة حسب مشروع الويكي'
